apiVersion: v1
kind: Service
metadata:
  name: tax-compliance-service-loadbalancer
  annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: tax-compliance
  ports:
    - protocol: TCP
      port: 80       # The public port exposed to the internet
      targetPort: 8080 # The internal port your Spring Boot app is listening on